server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_nguoi_dung
    username: root
    password:

  jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # ✅ giữ camelCase
      show-sql: true
      properties:
        hibernate:
          format_sql: true

jwt:
  secret: epigrid-secret-key-very-long-12345678901234567890
  expiration: 86400000


